export type NoteName = 'C' | 'D' | 'E' | 'F' | 'G' | 'A' | 'B';

export const A: NoteName = 'A';
export const B: NoteName = 'B';
export const C: NoteName = 'C';
export const D: NoteName = 'D';
export const E: NoteName = 'E';
export const F: NoteName = 'F';
export const G: NoteName = 'G';

export type NoteAccidental = '♯' | '♮' | '♭';

export const BEMOL: NoteAccidental = '♭';
export const NATURAL: NoteAccidental = '♮';
export const SHARP: NoteAccidental = '♯';

export type NoteType = {
  midiId: number;
  frequency: number;
  name?: NoteName;
  accidental?: NoteAccidental;
  octave?: number;
  pianoKey?: number;
};

export const emptyNote: NoteType = {
  midiId: -1,
  frequency: 0,
};

export const notes: NoteType[] = [
  {
    midiId: 0,
    frequency: 8.1758,
    name: C,
    octave: -1,
  },
  {
    midiId: 1,
    frequency: 8.66196,
    name: D,
    accidental: BEMOL,
    octave: -1,
  },
  {
    midiId: 2,
    frequency: 9.17702,
    name: D,
    octave: -1,
  },
  {
    midiId: 3,
    frequency: 9.72272,
    name: E,
    accidental: BEMOL,
    octave: -1,
  },
  {
    midiId: 4,
    frequency: 10.3009,
    name: E,
    octave: -1,
  },
  {
    midiId: 5,
    frequency: 10.9134,
    name: F,
    octave: -1,
  },
  {
    midiId: 6,
    frequency: 11.5623,
    name: G,
    accidental: BEMOL,
    octave: -1,
  },
  {
    midiId: 7,
    frequency: 12.2499,
    name: G,
    octave: -1,
  },
  {
    midiId: 8,
    frequency: 12.9783,
    name: A,
    accidental: BEMOL,
    octave: -1,
  },
  {
    midiId: 9,
    frequency: 13.75,
    name: A,
    octave: -1,
  },
  {
    midiId: 10,
    frequency: 14.5676,
    name: B,
    accidental: BEMOL,
    octave: -1,
  },
  {
    midiId: 11,
    frequency: 15.4339,
    name: B,
    octave: -1,
  },
  {
    midiId: 12,
    frequency: 16.3516,
    name: C,
    octave: 0,
  },
  {
    midiId: 13,
    frequency: 17.3239,
    name: D,
    accidental: BEMOL,
    octave: 0,
  },
  {
    midiId: 14,
    frequency: 18.354,
    name: D,
    octave: 0,
  },
  {
    midiId: 15,
    frequency: 19.4454,
    name: E,
    accidental: BEMOL,
    octave: 0,
  },
  {
    midiId: 16,
    frequency: 20.6017,
    name: E,
    octave: 0,
  },
  {
    midiId: 17,
    frequency: 21.8268,
    name: F,
    octave: 0,
  },
  {
    midiId: 18,
    frequency: 23.1247,
    name: G,
    accidental: BEMOL,
    octave: 0,
  },
  {
    midiId: 19,
    frequency: 24.4997,
    name: G,
    octave: 0,
  },
  {
    midiId: 20,
    frequency: 25.9565,
    name: A,
    accidental: BEMOL,
    octave: 0,
  },
  {
    midiId: 21,
    frequency: 27.5,
    name: A,
    octave: 0,
    pianoKey: 1,
  },
  {
    midiId: 22,
    frequency: 29.1352,
    name: B,
    accidental: BEMOL,
    octave: 0,
    pianoKey: 2,
  },
  {
    midiId: 23,
    frequency: 30.8677,
    name: B,
    octave: 0,
    pianoKey: 3,
  },
  {
    midiId: 24,
    frequency: 32.7032,
    name: C,
    octave: 1,
    pianoKey: 4,
  },
  {
    midiId: 25,
    frequency: 34.6478,
    name: D,
    accidental: BEMOL,
    octave: 1,
    pianoKey: 5,
  },
  {
    midiId: 26,
    frequency: 36.7081,
    name: D,
    octave: 1,
    pianoKey: 6,
  },
  {
    midiId: 27,
    frequency: 38.8909,
    name: E,
    accidental: BEMOL,
    octave: 1,
    pianoKey: 7,
  },
  {
    midiId: 28,
    frequency: 41.2034,
    name: E,
    octave: 1,
    pianoKey: 8,
  },
  {
    midiId: 29,
    frequency: 43.6535,
    name: F,
    octave: 1,
    pianoKey: 9,
  },
  {
    midiId: 30,
    frequency: 46.2493,
    name: G,
    accidental: BEMOL,
    octave: 1,
    pianoKey: 10,
  },
  {
    midiId: 31,
    frequency: 48.9994,
    name: G,
    octave: 1,
    pianoKey: 11,
  },
  {
    midiId: 32,
    frequency: 51.9131,
    name: A,
    accidental: BEMOL,
    octave: 1,
    pianoKey: 12,
  },
  {
    midiId: 33,
    frequency: 55.0,
    name: A,
    octave: 1,
    pianoKey: 13,
  },
  {
    midiId: 34,
    frequency: 58.2705,
    name: B,
    accidental: BEMOL,
    octave: 1,
    pianoKey: 14,
  },
  {
    midiId: 35,
    frequency: 61.7354,
    name: B,
    octave: 1,
    pianoKey: 15,
  },
  {
    midiId: 36,
    frequency: 65.4064,
    name: C,
    octave: 2,
    pianoKey: 16,
  },
  {
    midiId: 37,
    frequency: 69.2957,
    name: D,
    accidental: BEMOL,
    octave: 2,
    pianoKey: 17,
  },
  {
    midiId: 38,
    frequency: 73.4162,
    name: D,
    octave: 2,
    pianoKey: 18,
  },
  {
    midiId: 39,
    frequency: 77.7817,
    name: E,
    accidental: BEMOL,
    octave: 2,
    pianoKey: 19,
  },
  {
    midiId: 40,
    frequency: 82.4069,
    name: E,
    octave: 2,
    pianoKey: 20,
  },
  {
    midiId: 41,
    frequency: 87.3071,
    name: F,
    octave: 2,
    pianoKey: 21,
  },
  {
    midiId: 42,
    frequency: 92.4986,
    name: G,
    accidental: BEMOL,
    octave: 2,
    pianoKey: 22,
  },
  {
    midiId: 43,
    frequency: 97.9989,
    name: G,
    octave: 2,
    pianoKey: 23,
  },
  {
    midiId: 44,
    frequency: 103.826,
    name: A,
    accidental: BEMOL,
    octave: 2,
    pianoKey: 24,
  },
  {
    midiId: 45,
    frequency: 110.0,
    name: A,
    octave: 2,
    pianoKey: 25,
  },
  {
    midiId: 46,
    frequency: 116.541,
    name: B,
    accidental: BEMOL,
    octave: 2,
    pianoKey: 26,
  },
  {
    midiId: 47,
    frequency: 123.471,
    name: B,
    octave: 2,
    pianoKey: 27,
  },
  {
    midiId: 48,
    frequency: 130.813,
    name: C,
    octave: 3,
    pianoKey: 28,
  },
  {
    midiId: 49,
    frequency: 138.591,
    name: D,
    accidental: BEMOL,
    octave: 3,
    pianoKey: 29,
  },
  {
    midiId: 50,
    frequency: 146.832,
    name: D,
    octave: 3,
    pianoKey: 30,
  },
  {
    midiId: 51,
    frequency: 155.563,
    name: E,
    accidental: BEMOL,
    octave: 3,
    pianoKey: 31,
  },
  {
    midiId: 52,
    frequency: 164.814,
    name: E,
    octave: 3,
    pianoKey: 32,
  },
  {
    midiId: 53,
    frequency: 174.614,
    name: F,
    octave: 3,
    pianoKey: 33,
  },
  {
    midiId: 54,
    frequency: 184.997,
    name: G,
    accidental: BEMOL,
    octave: 3,
    pianoKey: 34,
  },
  {
    midiId: 55,
    frequency: 195.998,
    name: G,
    octave: 3,
    pianoKey: 35,
  },
  {
    midiId: 56,
    frequency: 207.652,
    name: A,
    accidental: BEMOL,
    octave: 3,
    pianoKey: 36,
  },
  {
    midiId: 57,
    frequency: 220.0,
    name: A,
    octave: 3,
    pianoKey: 37,
  },
  {
    midiId: 58,
    frequency: 233.082,
    name: B,
    accidental: BEMOL,
    octave: 3,
    pianoKey: 38,
  },
  {
    midiId: 59,
    frequency: 246.942,
    name: B,
    octave: 3,
    pianoKey: 39,
  },
  {
    midiId: 60,
    frequency: 261.626,
    name: C,
    octave: 4,
    pianoKey: 40,
  },
  {
    midiId: 61,
    frequency: 277.183,
    name: D,
    accidental: BEMOL,
    octave: 4,
    pianoKey: 41,
  },
  {
    midiId: 62,
    frequency: 293.665,
    name: D,
    octave: 4,
    pianoKey: 42,
  },
  {
    midiId: 63,
    frequency: 311.127,
    name: E,
    accidental: BEMOL,
    octave: 4,
    pianoKey: 43,
  },
  {
    midiId: 64,
    frequency: 329.628,
    name: E,
    octave: 4,
    pianoKey: 44,
  },
  {
    midiId: 65,
    frequency: 349.228,
    name: F,
    octave: 4,
    pianoKey: 45,
  },
  {
    midiId: 66,
    frequency: 369.994,
    name: G,
    accidental: BEMOL,
    octave: 4,
    pianoKey: 46,
  },
  {
    midiId: 67,
    frequency: 391.995,
    name: G,
    octave: 4,
    pianoKey: 47,
  },
  {
    midiId: 68,
    frequency: 415.305,
    name: A,
    accidental: BEMOL,
    octave: 4,
    pianoKey: 48,
  },
  {
    midiId: 69,
    frequency: 440.0,
    name: A,
    octave: 4,
    pianoKey: 49,
  },
  {
    midiId: 70,
    frequency: 466.164,
    name: B,
    accidental: BEMOL,
    octave: 4,
    pianoKey: 50,
  },
  {
    midiId: 71,
    frequency: 493.883,
    name: B,
    octave: 4,
    pianoKey: 51,
  },
  {
    midiId: 72,
    frequency: 523.251,
    name: C,
    octave: 5,
    pianoKey: 52,
  },
  {
    midiId: 73,
    frequency: 554.365,
    name: D,
    accidental: BEMOL,
    octave: 5,
    pianoKey: 53,
  },
  {
    midiId: 74,
    frequency: 587.33,
    name: D,
    octave: 5,
    pianoKey: 54,
  },
  {
    midiId: 75,
    frequency: 622.254,
    name: E,
    accidental: BEMOL,
    octave: 5,
    pianoKey: 55,
  },
  {
    midiId: 76,
    frequency: 659.255,
    name: E,
    octave: 5,
    pianoKey: 56,
  },
  {
    midiId: 77,
    frequency: 698.456,
    name: F,
    octave: 5,
    pianoKey: 57,
  },
  {
    midiId: 78,
    frequency: 739.989,
    name: G,
    accidental: BEMOL,
    octave: 5,
    pianoKey: 58,
  },
  {
    midiId: 79,
    frequency: 783.991,
    name: G,
    octave: 5,
    pianoKey: 59,
  },
  {
    midiId: 80,
    frequency: 830.609,
    name: A,
    accidental: BEMOL,
    octave: 5,
    pianoKey: 60,
  },
  {
    midiId: 81,
    frequency: 880.0,
    name: A,
    octave: 5,
    pianoKey: 61,
  },
  {
    midiId: 82,
    frequency: 932.328,
    name: B,
    accidental: BEMOL,
    octave: 5,
    pianoKey: 62,
  },
  {
    midiId: 83,
    frequency: 987.767,
    name: B,
    octave: 5,
    pianoKey: 63,
  },
  {
    midiId: 84,
    frequency: 1046.5,
    name: C,
    octave: 6,
    pianoKey: 64,
  },
  {
    midiId: 85,
    frequency: 1108.73,
    name: D,
    accidental: BEMOL,
    octave: 6,
    pianoKey: 65,
  },
  {
    midiId: 86,
    frequency: 1174.66,
    name: D,
    octave: 6,
    pianoKey: 66,
  },
  {
    midiId: 87,
    frequency: 1244.51,
    name: E,
    accidental: BEMOL,
    octave: 6,
    pianoKey: 67,
  },
  {
    midiId: 88,
    frequency: 1318.51,
    name: E,
    octave: 6,
    pianoKey: 68,
  },
  {
    midiId: 89,
    frequency: 1396.91,
    name: F,
    octave: 6,
    pianoKey: 69,
  },
  {
    midiId: 90,
    frequency: 1479.98,
    name: G,
    accidental: BEMOL,
    octave: 6,
    pianoKey: 70,
  },
  {
    midiId: 91,
    frequency: 1567.98,
    name: G,
    octave: 6,
    pianoKey: 71,
  },
  {
    midiId: 92,
    frequency: 1661.22,
    name: A,
    accidental: BEMOL,
    octave: 6,
    pianoKey: 72,
  },
  {
    midiId: 93,
    frequency: 1760.0,
    name: A,
    octave: 6,
    pianoKey: 73,
  },
  {
    midiId: 94,
    frequency: 1864.66,
    name: B,
    accidental: BEMOL,
    octave: 6,
    pianoKey: 74,
  },
  {
    midiId: 95,
    frequency: 1975.53,
    name: B,
    octave: 6,
    pianoKey: 75,
  },
  {
    midiId: 96,
    frequency: 2093.0,
    name: C,
    octave: 7,
    pianoKey: 76,
  },
  {
    midiId: 97,
    frequency: 2217.46,
    name: D,
    accidental: BEMOL,
    octave: 7,
    pianoKey: 77,
  },
  {
    midiId: 98,
    frequency: 2349.32,
    name: D,
    octave: 7,
    pianoKey: 78,
  },
  {
    midiId: 99,
    frequency: 2489.02,
    name: E,
    accidental: BEMOL,
    octave: 7,
    pianoKey: 79,
  },
  {
    midiId: 100,
    frequency: 2637.02,
    name: E,
    octave: 7,
    pianoKey: 80,
  },
  {
    midiId: 101,
    frequency: 2793.83,
    name: F,
    octave: 7,
    pianoKey: 81,
  },
  {
    midiId: 102,
    frequency: 2959.96,
    name: G,
    accidental: BEMOL,
    octave: 7,
    pianoKey: 82,
  },
  {
    midiId: 103,
    frequency: 3135.96,
    name: G,
    octave: 7,
    pianoKey: 83,
  },
  {
    midiId: 104,
    frequency: 3322.44,
    name: A,
    accidental: BEMOL,
    octave: 7,
    pianoKey: 84,
  },
  {
    midiId: 105,
    frequency: 3520.0,
    name: A,
    octave: 7,
    pianoKey: 85,
  },
  {
    midiId: 106,
    frequency: 3729.31,
    name: B,
    accidental: BEMOL,
    octave: 7,
    pianoKey: 86,
  },
  {
    midiId: 107,
    frequency: 3951.07,
    name: B,
    octave: 7,
    pianoKey: 87,
  },
  {
    midiId: 108,
    frequency: 4186.01,
    name: C,
    octave: 8,
    pianoKey: 88,
  },
  {
    midiId: 109,
    frequency: 4434.92,
    name: D,
    accidental: BEMOL,
    octave: 8,
    pianoKey: 89,
  },
  {
    midiId: 110,
    frequency: 4698.64,
    name: D,
    octave: 8,
    pianoKey: 90,
  },
  {
    midiId: 111,
    frequency: 4978.03,
    name: E,
    accidental: BEMOL,
    octave: 8,
    pianoKey: 91,
  },
  {
    midiId: 112,
    frequency: 5274.04,
    name: E,
    octave: 8,
    pianoKey: 92,
  },
  {
    midiId: 113,
    frequency: 5587.65,
    name: F,
    octave: 8,
    pianoKey: 93,
  },
  {
    midiId: 114,
    frequency: 5919.91,
    name: G,
    accidental: BEMOL,
    octave: 8,
    pianoKey: 94,
  },
  {
    midiId: 115,
    frequency: 6271.93,
    name: G,
    octave: 8,
    pianoKey: 95,
  },
  {
    midiId: 116,
    frequency: 6644.88,
    name: A,
    accidental: BEMOL,
    octave: 8,
    pianoKey: 96,
  },
  {
    midiId: 117,
    frequency: 7040.0,
    name: A,
    octave: 8,
    pianoKey: 97,
  },
  {
    midiId: 118,
    frequency: 7458.62,
    name: B,
    accidental: BEMOL,
    octave: 8,
    pianoKey: 98,
  },
  {
    midiId: 119,
    frequency: 7902.13,
    name: B,
    octave: 8,
    pianoKey: 99,
  },
  {
    midiId: 120,
    frequency: 8372.02,
    name: C,
    octave: 9,
    pianoKey: 100,
  },
  {
    midiId: 121,
    frequency: 8869.84,
    name: D,
    accidental: BEMOL,
    octave: 9,
    pianoKey: 101,
  },
  {
    midiId: 122,
    frequency: 9397.27,
    name: D,
    octave: 9,
    pianoKey: 102,
  },
  {
    midiId: 123,
    frequency: 9956.06,
    name: E,
    accidental: BEMOL,
    octave: 9,
    pianoKey: 103,
  },
  {
    midiId: 124,
    frequency: 10548.08,
    name: E,
    octave: 9,
    pianoKey: 104,
  },
  {
    midiId: 125,
    frequency: 11175.3,
    name: F,
    octave: 9,
    pianoKey: 105,
  },
  {
    midiId: 126,
    frequency: 11839.8,
    name: G,
    accidental: BEMOL,
    octave: 9,
    pianoKey: 106,
  },
  {
    midiId: 127,
    frequency: 12543.9,
    name: G,
    octave: 9,
    pianoKey: 107,
  },
  {
    midiId: 128,
    frequency: 13289.8,
    name: A,
    accidental: BEMOL,
    octave: 9,
    pianoKey: 108,
  },
];
